stages:
  - build
  
variables:
  gitlab_user:       "build.bot.0.cis.paas"
  gitlab_host:       "128.107.14.75"
  gitlab_port:       "443"
  slack:             "http://ci-secret-config/slack.sh"
  config_url:        "http://ci-secret-config/slack.url"
  secret_url:        "http://ci-secret-config/kubeconfig"
  deploy_yaml:       "http://ci-secret-config/deploy.yaml"
  debug:             "1"
  registry:          "k8s-docker-registry:5000"
  GIT_SSL_NO_VERIFY: "1"
  GIT_SSL_CAINFO:    "${HOME}/.private/gitlab.crt"


build-template:
  stage: build
  script: 
    - export GOPATH=/go
    - export PATH=${GOPATH}/bin:${PATH}
    - echo "${HOSTNAME}" $(pwd) $(date)
    - wget -O bin/slack.sh ${slack};
    - chmod +x bin/slack.sh
    - step=build
    - ./build
    - rc=$?
    - if (( debug )); then echo bin/slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
    - bin/slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
    - step=dockerize
    - ./dockerize
    - rc=$?
    - if (( debug )); then echo bin/slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}; fi
    - bin/slack.sh --step=${step} --gitlab-host=${gitlab_host} --gitlab-port=${gitlab_port} --gitlab-user=${gitlab_user} --slack-url=${config_url} --rc=${?}
  only:
    - master
  tags:
    - shell
    - ssh
